### ISSUE TITLE
Missing 'id' attributes for Form Inputs in Contact Form

### ISSUE THREAD

**Issue by AbePlays** [isaac-mcfadyen/personal-site#4]
Hi Isaac,

I've observed that the contact form inputs are not associated with their respective labels. While the labels have the "for" attribute set, the inputs are missing the corresponding "id" attributes. Is this intentional?

**Comment by isaac-mcfadyen** [comment]
Hi! You're right, thanks for catching that - it wasn't intentional.

Feel free to PR and I'll assign the `hacktoberfest` label, or I can PR myself if you want 🙂

**Comment by AbePlays** [comment]
Sounds great! I'll open a PR tomorrow morning.
